# name = input("what is your name")
# age = input("what is your age")
# friend = input("what is friends name")
# print("your name is " + name )
# print("your age is " + age)
# print("your friend is "+ friend)
# name, age, friend = input("enter your name, age and friend").split("  ")
name, age, friend = input("enter three numbers comma seprated").split(",")
print("your name is " + name )
print("your age is " + age)
print("your friend is "+ friend)